'use client';
import Container from '@mui/material/Container';
// import AppTheme from './theme/AppTheme';
// import AppAppBar from '@/components/AppBar';
import Footer from '../components/Footer';
import BlogHeader from '../components/BlogHeader'
import { Geist, Geist_Mono } from "next/font/google";
import { CacheProvider } from '@emotion/react';
import { ThemeProvider, CssBaseline } from '@mui/material';
import { createEmotionCache } from '../createEmotionCache';
import Toolbar from '@mui/material/Toolbar';
import theme from './theme';
import "./globals.css";

const clientCache = createEmotionCache();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CacheProvider value={clientCache}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            {/* <Toolbar /> */}
            <BlogHeader />
            <Container maxWidth="xl" component="main" sx={{ py: 4 }}>
              {children}
            </Container>
            <Footer />
          </ThemeProvider>
        </CacheProvider>
        {/* <AppAppBar />
        <Container
          maxWidth="lg"
          component="main"
          sx={{ display: 'flex', flexDirection: 'column', my: 16, gap: 4 }}
        >
          {children}
        </Container>
        <Footer /> */}
      </body>
    </html>
  );
}
