# Generated by Django 5.2.1 on 2025-05-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='post_images/'),
        ),
    ]
