# Generated by Django 5.1.7 on 2025-03-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_address1_userprofile_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('master_admin', 'Master Admin'), ('blog_admin', 'Blog Admin'), ('ai_video_editor_user', 'AI Video Editor User'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip_code',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
