# Generated by Django 5.2.1 on 2025-05-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blogpost_blog_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='blog_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
