# Generated by Django 5.2.1 on 2025-05-24 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blogmainpagesections_alter_uploadedimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmainpagesections',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Moderation flag for comments')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.blogpost')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for threaded replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment')),
                ('uploaded_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.uploadedimage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
