# Generated by Django 5.1.7 on 2025-03-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_phone_number_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='summery',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
