# Generated by Django 5.1 on 2025-04-11 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_summery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='media/content_images/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_detailed_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
