# Generated by Django 5.1 on 2025-04-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_uploadedimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='content_type',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/thumbnails/'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('master_admin', 'Master Admin'), ('blog_admin', 'Blog Admin'), ('ai_video_editor_user', 'AI Video Editor User'), ('user', 'User')], default='blog_admin', max_length=20),
        ),
    ]
