# Generated by Django 5.1.7 on 2025-03-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_is_verified_userprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_question',
            field=models.CharField(blank=True, choices=[('first_pet', 'What was the name of your first pet?'), ('mother_maiden', "What is your mother's maiden name?"), ('birth_city', 'In which city were you born?'), ('first_school', 'What was the name of your first school?'), ('favorite_teacher', 'Who was your favorite teacher?'), ('childhood_friend', 'What is the name of your best childhood friend?'), ('first_car', 'What was the make and model of your first car?'), ('favorite_place', 'What is your favorite vacation spot?'), ('parents_met', 'In which city did your parents meet?'), ('childhood_hero', 'Who was your childhood hero?')], default='', max_length=255),
        ),
    ]
